### ISSUE TITLE
Not working after flutter upgrade 

### ISSUE THREAD

**Issue by LostAnt** [kakajansh/echo#39]
Hi guys, everything worked fine before update on this config:

`flutter version: 1.22.6`

dependencies:
```yaml
  equatable: ^1.2.3
  flutter_bloc: ^6.0.1
  http: ^0.12.2
  flutter_secure_storage: ^3.3.3
  flutter_platform_widgets: ^0.60.2
  rxdart: ^0.24.1
  webview_flutter: ^1.0.7
  dio: ^3.0.10
  html: ^0.14.0+3
  socket_io_client: ^0.9.1
  laravel_echo:
  pull_to_refresh: ^1.6.0
  enum_to_string: ^1.0.11
  intl: ^0.16.1
  firebase_core: ^0.5.0+1
  firebase_analytics: ^6.0.2
  firebase_messaging: 8.0.0-dev.11
  grouped_list: ^3.5.0
  date_range_picker: ^1.0.6
  customizable_date_picker: ^0.0.3
  fluttertoast: ^7.1.1
  flutter_local_notifications: ^3.0.0
  dash_chat: ^1.1.15
  firebase_crashlytics: ^0.2.3
  mask_text_input_formatter: ^1.1.0
  flutter_launcher_icons: ^0.8.1
  local_auth:
    path: packages/local_auth-0.6.3+4
  image_picker: ^0.6.7+15
  cached_network_image: ^2.4.1
  photo_view: ^0.10.3
  path_provider: ^1.6.24
  flutter_pdfview: ^1.0.4
  permission_handler: ^5.0.1+1
  ext_storage:
  url_launcher: ^5.7.10
````

but after update to:
`flutter 2.0.3 and dart 2.12.2`

with dependencies: 
```yaml
  equatable: ^1.2.3
  flutter_bloc: ^6.0.1
  http: ^0.13.0
  flutter_secure_storage: ^4.1.0
  flutter_platform_widgets: ^0.80.0
  rxdart: ^0.24.1
  webview_flutter: ^1.0.7
  dio: ^4.0.0-prev1
  html: ^0.14.0+3
  socket_io_client: ^0.9.1
  laravel_echo:
  pull_to_refresh: ^1.6.4
  enum_to_string: ^1.0.11
  intl: ^0.17.0
  firebase_core: ^1.0.1
  firebase_analytics: ^7.1.1
  firebase_messaging: 9.0.0
  grouped_list: ^3.5.0
  date_range_picker:
    git:
      url: git://github.com/justkawal/date_range_picker.git
      ref: master
  customizable_date_picker:
    git:
      url: https://github.com/AyishaKP/customizable_date_picker.git
  fluttertoast: ^7.1.1
  flutter_local_notifications: ^5.0.0-nullsafety.1
  dash_chat: ^1.1.15-nullsafety
  firebase_crashlytics: ^1.0.0
  mask_text_input_formatter: ^1.1.0
  local_auth: ^1.1.0
  image_picker: ^0.7.3
  cached_network_image: ^2.5.1
  photo_view: ^0.10.3
  path_provider: ^2.0.1
  flutter_pdfview: ^1.0.4
  permission_handler: ^6.1.0
  ext_storage:
  mailer: ^3.2.1
  global_configuration: ^2.0.0-nullsafety.0
  google_fonts: ^2.0.0
  url_launcher: ^6.0.2
````

i can't connect to my laravel echo server. It's return timeout 
`flutter: connect_error`
`flutter: timeout`
`flutter: connect_timeout`
`flutter: 20000`

my connection code:
```
echo = new Echo({
          'broadcaster': 'socket.io',
          'client': IO.io,
          'namespace': 'Application.Lumen.Events',
          'auth': {
            'headers': {'Authorization': 'Bearer ${user.authToken}'}
          },
          'host': _chatEndpoint
        });
````

Any thoughts on this?
